### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by faridpo** [jaskie/PlayoutAutomation#14] opened 2016-10-12 12:58 UTC
i like to know:
1. when i have a 24/7 rundown/item has finnish played, does it delete or is a option to clean the all ready played
2. when insert a movie the cut transtions stop the item when finnish, can the mix transtions be default when inserted?
3. can i build a week playlist offline?
4. can 2 client instert media into the database?

**Comment by jaskie** [comment] 2016-10-12 13:30
Hi,
1. You have to delete outdated rundowns manually (as they are hierarchical, it's very simple).
2. Cut is currently default transition, so there should be a engine parameter (it requires coding).
3. It's currently possible only via second app installation, then save/open playlist, but i'ts rather inconvenient because playlist events are created using media files, so the same media should be accessible from both installations. This functionality would be easier to achieve when remote app access module will be finished (hence multi-user operations will be possible).
4. Currently, only one program instance may operate on single scheduling engine (see above). However, there is possible to place media files to server dirs (preferably, to primary server) using other means. The file appears in media folder (on Media tab) with `unknown` status. You can verify the file manually and then complete its metadata.

**Comment by faridpo** [comment] 2016-10-12 13:57
Hi, jackie

i need to build a new layout system for a new tv channel.
they want a playout in master, and a scheduler to build daily playlist and send to master
and if possible insert media/movies from a other pc
3. can you give a guide how can be achieve?.. with the remote app?
4. when i insert a media and metadata in a other pc, in the master layout i need to restart the app to see the changes..

**Comment by jaskie** [comment] 2016-10-12 14:41
Definitely, two instances should not work on the same engine/media directory. For your configuration, currently I would recommend building next-day playlist on main play-out PC while playing today's one (you may to switch off tracking to work convenient). 
It's also possible to import a playlist from external traffic management system. This can be done in two ways:
1. Using `Rundown->Load`. File format is relatively simple (save another to see it), and media binding is flexible:
   * first, using `MediaGuid` field, if it's available,
   * if not, using `IdAux`,
   * if failed, using `MediaName`, `MediaType`, `TcStart` and `Duration` simultaneously,
   * if yet not found, using only `FileName ` and `FileSize` fields.

2. Using UIPlugin ([example](https://github.com/jaskie/PlayoutAutomation/tree/master/Plugins/UiPluginExample) of such plugin is in project).

**Comment by faridpo** [comment] 2016-10-12 16:05
Hi, jackie

i like your software. 

I like to know what you mean with **(you may to switch off tracking to work convenient)**.

**Comment by jaskie** [comment] 2016-10-12 19:32
Thanks,
there is a two-state (pressed-depressed) `Track` button on rundown view. When it's pressed, view automatically follow playing elements (if they are expanded). So during rundown assembly it's better to switch it off.

**Comment by faridpo** [comment] 2016-10-12 19:42
Hi jackie,

Thank you, i like to know if the software will be updated to work with a scheduler to build playlist/planning?

you may know if a personal is working on the main playout for build a playlist, and if something must be change in the Onair playlist (breaking news -need to go live) ,,, in this situation you can't do nothing.

**Comment by faridpo** [comment] 2016-10-13 16:39
Hi jackie,

will be an update of the software in future?

**Comment by jaskie** [comment] 2016-10-13 16:56
Sorry,
I did not understood. What did you mean "scheduler"?
Of course, I plan to do further work, mainly to separate application core and user interface, some new useful features (e.g. quick playlist review, built-in player), improvements and bug fixes.
Kind regards --- Jurek

**Comment by faridpo** [comment] 2016-10-13 17:04
juke,
i mean for playlist creation, print playlist, as run log

I like to use your software in a project, but i need to deal the playlist creation, and know what is the next update,

or you can help with a idea for the playlist 
if i use a external traffic management system i can't not insert the "Live input" for build the play list

thank you

**Comment by sfahadshahzad** [comment] 2016-10-13 17:07
Hi Faridpo,

all the above mentioned feature which you are discussing already available out of the box.

you just need to configure the applications as per your rquirment or your workflow.

you can take live input simply adding an event for that you have to mention the input device in casparcg config file.

Regards,

Fahad

**Comment by faridpo** [comment] 2016-10-13 17:20
Hi Fahad,
thank you for your input, 
my issue is i have a server play (oniar) with the main playlist i want a to create the daily or weekly playlist on a other pc and load them on the Main play list ...
jackie write that i need to create the playlist on the main playlist and then save it...

that is why i ask if is a way the create playlist on other pc with connect with the same DB with the medias

**Comment by faridpo** [comment] 2016-10-13 17:32
Farah,
is possible you can give me a guide how to?

**Comment by jaskie** [comment] 2016-10-13 20:46
In fact, it should work. The second application instance should not damage media metadata nor existing playlist's information, assuming that you will ONLY build the new playlist on the second instance. However,  this playlist will not be visible from main instance until it restarts. This also can be done safely during play-out some longer programme (if it not finished during restart, rundown will continue).
But you should treat this as a temporary workaround, you should never add new media nor modify existing (esp. open on main instance) playlist - until app is fully networked.

**Comment by faridpo** [comment] 2016-10-14 05:19
jackie,
1. what do you mean "until app is fully networked." temporary workaround
2. do you have an update version coming out?
3.  is a way i can print the playlist/rundown?
4. when the default transition (cut) in the playlists set, the next movie/item would not Play,
The Next item/movie only play when i change the transitions to (mix)

**i have make a workaround (please advice)**
in mysql i create a username and password
in configuration i make a second engine rundown (i call it "Playlist")
i share the media drive and set in the media folder
open a second instance of the software on a second PC
and create the playlist in the "Playlist"instance, save the file
and load it in the Main Önair" playlist on the server pc

**Comment by jaskie** [comment] 2016-10-14 06:58
Hi,
1. It's planned to separate app core from UI using network communication. It should be ready within 2 months, as planned.
2. No, currently release is almost most recent version.
3. No, currently there is no print functionality at all. 
4. Please, provide some more information to replicate the issue, as it does not occur in my configuration (just verified again).

You workaround seems to be OK, with additional note, that you shall not do anything in media properties nor add them. To work more convenient, you should assign the "Playlist" engine to instance number (e.g.) 1 (in engine config), and set this number as instance in config file (first button in config program) - this will result that you will see only required engine in both installations.

**Comment by faridpo** [comment] 2016-10-14 12:37
jackie,

4. i try different scenario, i make a rundown insert 2 movie with cut transition, when i play the rundown it play the first movie, then it stop and the counter on the rundown contuene running, but no  video. 

i try the workaround , but is not work for me, i don't see that the instance or separate

here are some , pics

![tvplay01](https://cloud.githubusercontent.com/assets/22792685/19387597/417ba2d8-91e9-11e6-9795-263d6d005717.png)
![tvplay02](https://cloud.githubusercontent.com/assets/22792685/19387598/41927a3a-91e9-11e6-8791-ad67d887925f.png)

**Comment by faridpo** [comment] 2016-10-14 12:51
jackie,

here are a pic, of a other view that the counter and none video is playing


![tvplay03](https://cloud.githubusercontent.com/assets/22792685/19387991/67765760-91eb-11e6-9d05-94d63ad39a46.png)

**Comment by jaskie** [comment] 2016-10-14 13:48
Hi,
Thanks for screens, I confirmed that problem exists with NTSC frame rates. I've just made a quick fix to allow you do further tests. Updated version is in the same [release](https://github.com/jaskie/PlayoutAutomation/releases/latest).
To separate instances set the same number to field `Instance binding` field here:
![image](https://cloud.githubusercontent.com/assets/1919742/19389720/4d78f202-9225-11e6-9054-7430412ffd65.png) 
and here:
![image](https://cloud.githubusercontent.com/assets/1919742/19389769/861bf7ee-9225-11e6-8b0e-7a2563829b45.png)
to both installations.

**Comment by faridpo** [comment] 2016-10-14 14:15
Jackie,

i get an error when start the software, here a pic of the error

![tvplay-v2-error1](https://cloud.githubusercontent.com/assets/22792685/19390683/22e5ef28-91f7-11e6-967c-18cddc3635fb.png)

**Comment by jaskie** [comment] 2016-10-14 20:35
The error seems to be related with `CGElementsController` plugin. Indeed, I have no idea, why this error occurs at your installation, and not at mine.
As a workaround you can delete `.\Plugins\TAS.Server.CGElementsController.dll` file (I see that the plugin did't work at you at even before). Do you have valid `.\Configuration\Elements.xml` file?

**Comment by faridpo** [comment] 2016-10-14 21:49
Jackie,

i delete the .dll file and the software open
(advice)
i replace the old dll to the new updated software and it works too
 i am testing the update,,and is working Perfect,, thank you

I like to Know
How can use the cg elements feature and the crawls enable behavior, parental sign ,animations?

**Comment by jaskie** [comment] 2016-10-14 22:09
The `CGElementsController` in the project is de facto an example that shows its functionality. To use it in production you have to make your own component based on it, and add code to execute actions when elements state changes. It's not very complex... and rather depends on what particular device you want to control.

**Comment by jaskie** [comment] 2016-10-14 22:19
You can i.e. write a flash [template](http://forum.casparcg.com/viewtopic.php?f=5&t=1375) to work on CasparCG capable to display these, which will connect to the plugin via TCP and listen for commands.

**Comment by jaskie** [comment] 2016-10-15 09:11
Static graphic overlays (a simple logo and parental signs) you can add directly from application using these ![sign](https://github.com/jaskie/PlayoutAutomation/blob/master/TAS.Client.Common/Images/Layers/Layer1.png?raw=true) ![sign](https://github.com/jaskie/PlayoutAutomation/blob/master/TAS.Client.Common/Images/Layers/Layer2.png?raw=true) ![sign](https://github.com/jaskie/PlayoutAutomation/blob/master/TAS.Client.Common/Images/Layers/Layer3.png?raw=true) buttons.

**Comment by BuryPaul** [comment] 2016-10-17 04:10
When adding logos or parental signs using one of the 3 buttons how does one position the graphics on the screen?

**Comment by faridpo** [comment] 2016-10-17 04:20
jaskie
if i want the parental signs to fade in , and over 10 sec. fade out?

and the software don't see sub folder in the media folder?

**Comment by jaskie** [comment] 2016-10-17 06:13
To position logo, just make it full screen size with alpha channel, like [this](https://cloud.githubusercontent.com/assets/1919742/19426875/54dab1ee-9440-11e6-9673-2c645d524adf.png).
Currently, logo at layers shows and hides using "cut" transition. It's easy to add fade-in transition, with fade-out is somewhat harder to work it out.
To control time span of logo appearance, expand item containing it, select inserted logo, and set `Duration` and `Delay` times (delay counts from start movie/live containing it).

**Comment by faridpo** [comment] 2016-10-17 13:07
jaskie

when i have a sub folder to organize my media, it don't show in the media?

**Comment by jaskie** [comment] 2016-10-17 13:48
No,
currently app does not see subfolders in server's media folders - it was simply not needed. To deal with high file volume, there are another means:

- media types and categories,
- searching and sorting,
- archiving (you have to configure an archive dir).

However, you can configure an ingest folder to track its subfolders, too, even if it's a remote FTP share. It's presented, however, as flat structure on media view.

**Comment by BuryPaul** [comment] 2016-10-18 04:51
Any possible way you can add instructions on getting the animations working to the wiki? I can add the demo animation files that came with the CasperCG server to the rundown by clicking the "A" button on individual "movies" but the animations don't playout at all. They all have a duration of 00:00:00:00 which causes them to start and immediately become marked as played.

**Comment by jaskie** [comment] 2016-10-18 07:42
Flash templates usage is strictly connected to its usage in CasparCG, please refer to [CasparCG documentation](http://casparcg.com/wiki/CasparCG_2.0_AMCP_Protocol#Template_Graphics_Commands). 
In TVPlay, you can invoke specific CG command at desired time with parameters - just add a template to rundown element, select the added template item, and set it's parameters:
![image](https://cloud.githubusercontent.com/assets/1919742/19467556/0f09883e-9512-11e6-90b5-0fcbe9270280.png)
(sorry that's is in Polish)
You can set either start delay, as well as CG layer, method and field values. Currently, TVPlay have no means to know how template displays, nor how long it lasts, however you can force its unload using `remove` or `clear` methods.
The problem, where normally working animations don't play at all may be caused by wrong CG layer setting - it defaults to -1, which is not allowed. To test how animation is working, I would rather recommend official [CasparCG client](https://sourceforge.net/projects/casparcg/files/CasparCG_Client/CasparCG_Client_2.0/).

**Comment by faridpo** [comment] 2016-10-18 15:58
jaskie

i can play a animation/template in casparcg client , when i load it in the tvplay with the same setting,
it not play,

**Comment by jaskie** [comment] 2016-10-18 16:15
Isn't wrong CG layer issue? 
You can debug this using Caspar's log file, to see difference between commands received from Caspar client and TVPlay. If you don't find any reason, send me the logfile too look at it (to PM address).

**Comment by faridpo** [comment] 2016-10-18 16:59
jaskie

It is working Now. thank you

**Comment by BuryPaul** [comment] 2016-10-19 00:57
Thank you Jaskie. The CG layer was exactly what was causing my problem. Keep up the good work. 

By the way the Polish language is no problem for me. I was born in Poland and can read and speak Polish well. Writing, not so much. hahaha

**Comment by faridpo** [comment] 2016-10-19 13:23
jaskie,

1. when i set the video format (NTSC) , and ingest (with no compression-copy only) i need to set it again when it done ingested

2. what is the "trails left"?

**Comment by jaskie** [comment] 2016-10-19 14:22
Immediately after ingest file is verified, video format and duration are checked again to commit proper ingest. Currently, during ingest file is't scaled (it was in previous versions, moreover: it's not possible without recompression). IMHO, NTSC files should be 640x486, 30fps interlaced, am I right?
`Trials left` (have I a typo?) is count, how many times the operation will try to execute (when it reaches zero, it will permanently fail). It allows to perform an operation when file is in use for short time.

**Comment by faridpo** [comment] 2016-10-19 14:28
jaskie

The files are mpeg 2 (720x480) and mp4(1920x1080) interlaced

what you explain is: that when i ingest a file (mpeg2) it will always recompress to a .mov file?

**Comment by jaskie** [comment] 2016-10-19 14:43
Normal NTSC file is 720px width? I will correct this. I was only teached about NTSC, and never work with this format.
Files are not recompressed, they are only rewrapped to mov format. I once noticed, that it's most universal container, and that just left. However, no image nor audio quality is lost in the process - all packets are read from source and written back to new file. It also verifies that file container is OK (e.g. when file is clipped)

**Comment by faridpo** [comment] 2016-10-19 15:08
jackie

has the SMPTE 259M standard 480i (full frame) is 720x480
what i know 640x480 is for (VGA)

**Comment by jaskie** [comment] 2016-10-19 16:48
Thanks,
I will modify this tomorrow. 
I gave up with scaling the clips on ingest when applied bicubic rescale filter while playing clips to my fork of CasparCG, allowing to preserve original picture dimensions on server's folders. This generated another complexity with recompress bitrate calculation, which now is depended on frame height and user-controlled multiplier.

**Comment by faridpo** [comment] 2016-10-20 02:38
jaskie

can you help me, 
1. how to save a asrunlog everyday from the DB in .csv file
2, is the rundowns save in the DB? , that i can create a printed file of the rundown .csv file

**Comment by faridpo** [comment] 2016-10-21 12:25
jaskie

Any update?

**Comment by jaskie** [comment] 2016-10-24 11:55
Sorry for delay. It's [here](https://github.com/jaskie/PlayoutAutomation/releases/latest)

**Comment by faridpo** [comment] 2016-10-24 13:09
jaskie

Thank you, for the update...
this updated features of ?

**Comment by jaskie** [comment] 2016-10-24 17:02
Mainly NTSC format definition. Plus some housekeeping.

**Comment by faridpo** [comment] 2016-10-25 04:01
askie

can you help me, 
1. how to save a asrunlog everyday from the DB in .csv file
2, is the rundowns save in the DB? , that i can create a printed file of the rundown .csv file

**Comment by jaskie** [comment] 2016-10-25 06:25
faridpo,
I recommend you get familiar with some tool to manipulate data in MySQL tables - I use MySQL Workbench, which is also MySQL team product. There you can see all tables that exists in database, query the data, and save it to various formats, including csv. To automate these tasks, you will need probably do some coding. Keep in mind that database persists datetime fields in UTC.
Table `asrunlog` of course contains the as-run log, and table `rundownevent` contains rundown items.
Remaining tables contains:
- `archive` - archive directories,
- `archivemedia` - its media file's metadata,
- `engine` - configuration of scheduling engines,
- `server` - play-out server's configurations,
- `servermedia` - media metadata in server's directories,
- `media_templated` - auxiliary information when a media file is flash template,
- `mediasegments` - sub-clips of server or archive media items,
- `rundownevent_templated` - auxiliary information when rundown item is flash template,
- `params` - currently contains only database schema version.

**Comment by faridpo** [comment] 2016-10-31 13:51
jaskie

the cg elements, how i can use with my graphics or animation?
if a have a graphics with a parental signs , how the software send the commands to my graphics

i like to know more about the CG

**Comment by jaskie** [comment] 2016-11-01 18:08
farid,
it would be best if you familiarize yourself with CasparCG itself, particularly with templates creation and play-out them. The TVPlay functionality regarding templates is simple transposition of CasparCG SVT's client methods.
To start, I recommend you reading of [CasparCG wiki part concerning flash templates](http://casparcg.com/wiki/Content_/_Media#Flash_Templates).

**Comment by faridpo** [comment] 2016-11-02 01:20
jaskie
sorry 
the template creation is not the problem, what i mean is the cg part in the software
the crawl and the parental .

if i set the parental to # 18 in the media video , i need the command to set in the template?

**Comment by jaskie** [comment] 2016-11-02 07:33
farid,
these functionality is only scaffold to make your own channel branding solution. We are using it internally to control a Caspar template, but this particular solution couldn't be made public.
But having this scaffold it's relatively easy to build your own implementation. I'll also try to make it working out of the box in a free time.

**Comment by faridpo** [comment] 2016-11-03 16:07
jaskie,

Thankyou, if u can help, or give some tips where i can look for the commands

**Comment by faridpo** [comment] 2016-11-24 12:52
jaskie,
1. Can i run a AMCP command in the script ? or what cammnad can run?
2. the tvplay update wil be release this year?

**Comment by jaskie** [comment] 2016-11-24 13:20
Farid,
2. I moved releases to [GitHub](https://github.com/jaskie/PlayoutAutomation/releases)
1. Yes, but currently only subset of commands is supported.  Supported commands:

- MIXER FILL
- MIXER CLIP
- MIXER CLEAR
 

The commands are parsed, so  syntax is:
MIXER {LAYER} ...
where {LAYER} is layer name, one of:
- Program
- CG1
- CG2
- CG3
- CG4
- CG5
- Animation
- Preset
- Preview

**Comment by faridpo** [comment] 2016-11-24 13:28
jaskie,

thank you,

about the update that you mention about this feature:
_**"separate application core and user interface"**_

**Comment by jaskie** [comment] 2016-11-24 13:35
This particular functionality probably will be postponed 1-2 months - currently I have other assignments...

**Comment by faridpo** [comment] 2016-11-24 13:43
jaskie, oke

Can you help me with some exmaple of:
MIXER Program ......
MIXER Animation .....
MIXER Preset .....

**Comment by jaskie** [comment] 2016-11-24 13:47
The rest of command is identical as in original AMCP protocol, i.e.:
`MIXER PROGRAM FILL 0.587 0.135 0.373 0.45`
`MIXER PROGRAM CLEAR`
Currently, layers other than Program seems to be useless (should I remove it from syntax completely?)

**Comment by faridpo** [comment] 2016-11-24 14:05
oke, you have change "Layer" to Program?

if i have a video with logo or animation and need to Go to Commercial break need to clear the logo and animation, and back in when the video continue, how can be done

since i can run the animation on top of the video in the rundown

**Comment by jaskie** [comment] 2016-11-24 15:05
You can do this completely without manually using these MIXER commands. Just add animation event with `Add` method on clip when it should show, and with `Remove` method on clip without it.

**Comment by faridpo** [comment] 2016-11-29 10:10
JASKIE,

1. tvplay is using server 2.0.4, why?

2. does HEVC h.265 supported?

**Comment by jaskie** [comment] 2016-11-29 13:42
Farid,
1.  We are using a fork of version 2.06. Brief description of changes is [here](https://github.com/jaskie/Server). It's because:

- HTML producer wasn't required to our operation,
- the improvements we made weren't included in main branch.

2. It should be, as it depends on FFmpeg. However, it was never tested by me personally.

**Comment by faridpo** [comment] 2016-11-29 15:24
Jaskie,

the link you send is for work with the prime Fork software?

and the public Release (TVPlay-2016-10-24) include a other version?

**Comment by jaskie** [comment] 2016-11-29 20:47
No, it's exactly the same fork - I only included binaries here. It has distinct revision numbering included, current one is AFIR 4.8.

**Comment by faridpo** [comment] 2016-12-01 17:55
JASKIE,

1. My is 2.0.6 TVP rev. 4.5 stable
2. the aspect ratio control is not working for me,

the format is 1080i 5994, and i have a mix of SD 4x3 and HD 1080i videos
the SD 4x3 video stretch to 16x9, i want they play in correct aspect ratio ( pillar box)

**Comment by jaskie** [comment] 2016-12-01 19:44
Set following:
In TVPlay.config.exe -> Rundown engines -> Aspect ratio control = Image resize,
4:3 media should have Video Format = NTSC
It should work, however I didn't tested it. Let me know if not, I'll fix it.

**Comment by faridpo** [comment] 2016-12-01 19:48
jaskie,

i have set the aspect ratio in config to Image Size, and is not work (NTSC)

**Comment by jaskie** [comment] 2016-12-01 20:09
Mind also clip properties. It must have Video Format set to NTSC (4:3). Is it OK?
![image](https://cloud.githubusercontent.com/assets/1919742/20810535/5fe0ebce-b80a-11e6-80f3-1a2856851f85.png)

**Comment by faridpo** [comment] 2016-12-01 20:13
jaskie,
if i set the video format of the video NTSC, i dont see it in the playlist to add in the list,
i see only the format of the rundown.

**Comment by jaskie** [comment] 2016-12-01 20:34
Can you make it in reverse order (first add to playlist, then change video format and finally play it)?

**Comment by faridpo** [comment] 2016-12-02 18:34
jaskie,

Yes when set in media to the playout format(1080i) and insert in the playlist and change it back in Media to ntsc 4x3, it playback with the correct aspect ratio.
question is:

why  can not see all format in the playlist? it can be fix?

**Comment by faridpo** [comment] 2016-12-02 19:12
jaskie,
i notes , when i go back in the media after i change the format to NTSC 4x3 i cant preview the video anymore

**Comment by jaskie** [comment] 2016-12-02 20:37
Yes, system requires media to have exactly same frame rate as engine to be able to put media to playlist or preview it. Therefore I have to make second NTSC format that have 29,97 fps (the existing one is 30 fps). Can you provide me some files in that format (and also HD with this framerate) for testing?
How should I format timecode for that framerate?

**Comment by faridpo** [comment] 2016-12-02 23:28
Jaskie,

where can i upload the files for you?

**Comment by jaskie** [comment] 2016-12-03 10:16
Where is convenient for you (Google Drive, etc.), but rather send me a private mail with the link instead presenting it here; of course if you don't want these files to spread over Internet ;-)
I can also setup an upload site for you over http or ftp.

**Comment by faridpo** [comment] 2016-12-03 12:29
jaskie,

i have send you a email with link

let me know

**Closed** 2018-02-27 08:11 UTC
